#FROM node:16  
# WORKDIR /app  
# COPY package*.json ./  
# RUN npm install  
# COPY . .  
# EXPOSE 8080  
# CMD ["npm", "run", "serve"] 

FROM node:16 AS build-stage
WORKDIR /app
COPY package*.json ./
RUN npm install --legacy-peer-deps
COPY . .
RUN npm run build

FROM nginx:alpine
COPY --from=build-stage /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]

